server:
  port: 9411
spring:
  application:
    name: hystrix-demo2
#  sleuth:
#    enabled: false
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/world?serverTimezone=Asia/Shanghai
#    username: root
#    password: root123



#zipkin:
#  storage:
#    type: mysql
#  zipkin:
#    base-url: http://localhost:9411
#logging:
#  level:
#    root: INFO
#    org.springframework.web.servlet.DispatcherServlet: DEBUG